# Generated by Django 3.1.12 on 2021-07-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True, verbose_name='question')),
                ('answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='answer')),
            ],
        ),
    ]
