# Generated by Django 3.1.12 on 2021-08-11 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='view',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=25, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewUser', to=settings.AUTH_USER_MODEL, verbose_name='viewUser')),
            ],
            options={
                'unique_together': {('project', 'user')},
                'index_together': {('project', 'user')},
            },
        ),
    ]
