# Generated by Django 3.1.12 on 2021-07-28 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('sessions', models.IntegerField()),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statsReport', to='views.view', verbose_name='statsReport')),
            ],
        ),
    ]
