# Generated by Django 3.1.12 on 2021-07-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0002_stats'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stats',
            index=models.Index(fields=['view_id'], name='stats_view_index'),
        ),
        migrations.AddIndex(
            model_name='stats',
            index=models.Index(fields=['view_id', 'url'], name='stats_url_index'),
        ),
    ]
