# Generated by Django 3.1.12 on 2021-07-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0003_auto_20210728_2106'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['user'], name='views_user_index'),
        ),
    ]
