# Generated by Django 3.1.12 on 2021-07-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ahrefs_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='ahrefs_token'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='google_token'),
        ),
    ]
