# Generated by Django 3.1.12 on 2021-07-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210710_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ahrefs_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ahrefs_token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='google_token'),
        ),
    ]
