# Generated by Django 3.1.12 on 2021-07-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210720_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='google_token',
            new_name='google_api_token',
        ),
        migrations.AddField(
            model_name='user',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='google_token'),
        ),
    ]
