# Generated by Django 3.1.12 on 2021-07-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=100)),
                ('fechaDesde', models.DateTimeField(auto_now_add=True)),
                ('fechaHasta', models.DateTimeField(auto_now_add=True)),
                ('providers', models.ManyToManyField(to='provider.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='provider.provider', verbose_name='user')),
            ],
        ),
    ]
