# Generated by Django 3.1.12 on 2021-07-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='creationDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='dateFrom',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='dateTo',
            field=models.DateTimeField(),
        ),
    ]
