# Generated by Django 3.1.12 on 2021-07-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
