# Generated by Django 3.1.12 on 2021-07-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.CharField(blank=True, max_length=255, verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Report name'),
        ),
    ]
