# Generated by Django 3.1.12 on 2021-07-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20210716_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='dateFrom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='dateTo',
            field=models.DateField(),
        ),
    ]
