# Generated by Django 3.1.12 on 2021-07-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20210718_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('canceled', 'canceled'), ('created', 'created'), ('failed', 'failed')], default='pending', help_text='Report status', max_length=8),
        ),
    ]
