# Generated by Django 3.1.12 on 2021-07-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='thresholds',
            field=models.JSONField(default='{}'),
        ),
    ]
