# Generated by Django 3.1.12 on 2021-07-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_thresholds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='thresholds',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
