# Generated by Django 3.1.12 on 2021-07-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20210720_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sitemap',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sitemap'),
        ),
    ]
