# Generated by Django 3.1.12 on 2021-07-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_sitemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.CharField(max_length=255, verbose_name='project'),
        ),
    ]
