# Generated by Django 3.1.12 on 2021-07-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20210722_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('process', 'Processing'), ('canceled', 'Canceled'), ('created', 'Created'), ('failed', 'Failed')], default='pending', help_text='Report status', max_length=8),
        ),
    ]
