# Generated by Django 3.1.12 on 2021-07-24 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20210724_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='processingEndDate',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='processingEndDate'),
        ),
        migrations.AlterField(
            model_name='report',
            name='processingStartDate',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='processingStartDate'),
        ),
    ]
