# Generated by Django 3.1.12 on 2021-07-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20210724_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='processingEndDate',
        ),
        migrations.RemoveField(
            model_name='report',
            name='processingStartDate',
        ),
    ]
