# Generated by Django 3.1.12 on 2021-07-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20210724_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='processingEndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='processingStartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
