# Generated by Django 3.1.12 on 2021-07-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20210724_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='key'),
        ),
        migrations.AddField(
            model_name='report',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='path'),
        ),
    ]
