# Generated by Django 3.1.12 on 2021-07-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20210724_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('process', 'Processing'), ('canceled', 'Canceled'), ('created', 'Created'), ('failed', 'Failed'), ('complete', 'Completed')], default='pending', help_text='Report status', max_length=8),
        ),
    ]
