# Generated by Django 3.1.12 on 2021-07-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20210727_2156'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user'], name='reports_user_index'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', 'project'], name='reports_project_index'),
        ),
    ]
