# Generated by Django 3.1.12 on 2021-07-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20210727_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sitemap',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
