# Generated by Django 3.1.12 on 2021-07-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20210728_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sitemap',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
