# Generated by Django 3.1.12 on 2021-08-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20210728_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='thresholds',
        ),
    ]
