# Generated by Django 3.1.12 on 2021-08-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20210728_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='url')),
                ('is_accepted_status', models.CharField(blank=True, choices=[('accept', 'Accept'), ('block', 'Block')], default='', max_length=6)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='reports.report', verbose_name='report')),
            ],
        ),
    ]
