# Generated by Django 3.1.12 on 2021-08-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_auto_20210805_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='allowedUrlsPath',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Allowed URLS'),
        ),
        migrations.AddField(
            model_name='report',
            name='bannedUrlsPath',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banned URLS'),
        ),
        migrations.DeleteModel(
            name='reportURL',
        ),
    ]
