# Generated by Django 3.1.12 on 2021-08-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_auto_20210811_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dashboard',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
