# Generated by Django 3.1.12 on 2021-07-03 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requestdemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdemo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
